table-booking-modal
DmytoStas/team-8-html pull request #9
Opened 2023-03-03 20:45 UTC by Nichkoss

2023-03-03 23:45 UTC, DmytoStas requested changes

2023-03-03 23:45 UTC, DmytoStas commented on src/partials/modals.html
> +        <strong>BOOK <em>A TABLE</em></strong>
strong краще замінити заголовком h2, так як на макеті там жирність 500,а strong зробить 700 і ти це в css не зміниш
Замість em краще просто <i>. В нас на тому тексті ніякого акценту не робиться просто шрифт має бути Italic

2023-03-03 23:45 UTC, DmytoStas commented on src/partials/modals.html
> +        <svg class="" width="13.5" height="13.5">
Трішки неправильний розмір іконки. Глибоко в солях макету зайшла. Там є два розміри 32х32 та 28х28
Краще розмір для цих іконок не задавати у HTML файлі. Зробимо це через CSS так як розмір на різних девайсах змінюється

2023-03-03 23:45 UTC, DmytoStas commented on src/partials/modals.html
> +        <form action="" name="table_booking">
Атрибут action="" можна прибрати

2023-03-03 23:45 UTC, DmytoStas commented on src/partials/modals.html
> +            <div>
Ти вже сама можеш поміти, що в тебе велике нагромадження div тегів.
Їх стане менше якщо селекти та інпути помістити у label
В такому випадку і р-шки мають бути в середині label

2023-03-03 23:45 UTC, DmytoStas commented on src/partials/modals.html
> +                    <input type="text" id="table_person_name" name="table_person_name">
По ТЗ-шкі в input-ах має бути проста валідація з топомогою атрибута pattern=""

2023-03-04 02:04 UTC, Nichkoss commented on src/partials/modals.html
> +            <div>
я просто хочу відділити те що має лінією підкреслюватись , тобто поле вводу з нижнім бордером, а під ним р-шка
а зовнішній дів для їх однакового розташування між полями

2023-03-04 02:06 UTC, Nichkoss commented on src/partials/modals.html
> +        <svg class="" width="13.5" height="13.5">
добре, видалю з наступним комітом як треба буде ше шось змінити

2023-03-04 02:11 UTC, DmytoStas requested changes

2023-03-04 02:11 UTC, DmytoStas commented on src/partials/modals.html
> +        <use href="../img/sprite.svg#cross"></use>
Шлях до іконок пишемо починаючи з /
Id до іконки хрестика x-close

2023-03-04 03:17 UTC, DmytoStas approved these changes

2023-03-04 03:17 UTC, merged